swagger: '2.0'
info:
 title: PRL
 version: "1.0.0"


schemes:
 - http

basePath: /
produces:
 - application/json

paths:
 /launch/arm:
   post:
     description: arm the system
     responses:
       200:
         description: ok, armed

 /launch/disarm:
   post:
     description: disarm the system
     responses:
       200:
         description: ok, disarmed

 /launch/status:
   get:
     description: Returns status of all start tubes
     tags:
       - launch
     responses:
       200:
        description: An array of statuses
        schema:
          $ref: "#/definitions/Status"

 /launch/fire:
  post:
    description: Start the given rockets
    tags:
      - launch
    parameters:
    - name: tubeIds
      in: body
      description: Ids of the tubes to fire.
      required: true
      schema:
        type: array
        items:
          type: number
    responses:
      200:
        description: ok
      400:
        description: one of the tubes is empty

/move:
  get:
    description: get the status of the tower
    tags:
     - move
    responses:
      200:
        description: ok status returned
        schema:
          $ref: "#/definitions/TowerStatus"

  post:
    description: Starts or stops moving the tubes in a  direction
    tags:
      - move
    parameters:
    - name: Command
      in: body
      description: JSON object defining a command
      required: true
      schema:
        $ref: "#/definitions/Command"
    responses:
      200:
        description: ok command executed
        schema:
          $ref: "#/definitions/TowerStatus"
      400:
        description: bad request, invalid Command
      500:
        description: error during execution


definitions:
  Status:
    properties:
      "armed":
        type: boolean
      "tubes":
        type: array
        items:
          $ref: '#/definitions/TubeStatus'

  TubeStatus:
    properties:
      "id":
        type: number
      "loaded":
        type: boolean

  TowerStatus:
    properties:
      "movingdirections":
        type: array
        items:
          type: string

  Command:
    properties:
      "type":
        type: string
        description: enum of cmd, reset, test, service
      "direction":
        type: string
        description: enum of up, down, cw, ccw
      "action":
        type: string
        description: enum of start, stop

